from __future__ import annotations

from importlib.resources import files
from PySide6.QtCore import Qt, Signal, QSize
from PySide6.QtGui import QPixmap
from PySide6.QtWidgets import (
    QApplication, QCheckBox, QComboBox, QFrame, QHBoxLayout, QLabel, QLineEdit, QPlainTextEdit,
    QPushButton, QScrollArea, QTabWidget, QVBoxLayout, QWidget,
)

from .reading_widgets import QuestionEdit, ReadingResult


def section(text: str) -> QLabel:
    label = QLabel(text)
    label.setObjectName("Section")
    return label


def row(*widgets) -> QHBoxLayout:
    layout = QHBoxLayout()
    for widget in widgets:
        layout.addWidget(widget)
    return layout


class Sidebar(QWidget):
    closing = Signal()

    def __init__(self):
        super().__init__()
        self.setObjectName("Sidebar")
        self.setWindowTitle("StudyCopilot · 框选即翻译")
        self.setMinimumWidth(380)
        self.resize(430, 820)
        self.image = QPixmap()
        self.setStyleSheet(files("studycopilot").joinpath("ui/style.qss").read_text(encoding="utf-8"))
        outer = QVBoxLayout(self)
        outer.setContentsMargins(14, 14, 14, 12)
        header = QFrame()
        header.setObjectName("Header")
        heading = QVBoxLayout(header)
        heading.setContentsMargins(9, 5, 9, 5)
        heading.setSpacing(2)
        title = QLabel("StudyCopilot")
        title.setObjectName("Title")
        heading.addWidget(title)
        self.location = QPushButton("选择项目与资料  ▾")
        self.location.setStyleSheet("padding: 3px;")
        self.location.setCheckable(True)
        self.location.setToolTip("展开项目与资料管理")
        heading.addWidget(self.location)
        outer.addWidget(header)

        self.scroll = scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        body = QWidget()
        layout = QVBoxLayout(body)
        layout.setContentsMargins(0, 0, 2, 0)
        layout.setSpacing(6)
        scroll.setWidget(body)
        outer.addWidget(scroll, 1)

        self.settings_panel = QWidget()
        settings = QVBoxLayout(self.settings_panel)
        settings.setContentsMargins(0, 0, 0, 0)
        self.projects, self.sources = QComboBox(), QComboBox()
        for combo, name in ((self.projects, "projects"), (self.sources, "sources")):
            combo.setObjectName(name)
            combo.setMinimumContentsLength(6)
            combo.setSizeAdjustPolicy(QComboBox.SizeAdjustPolicy.AdjustToMinimumContentsLengthWithIcon)
        self.new_project, self.new_source = QPushButton("＋ 新建"), QPushButton("＋ 添加")
        settings.addWidget(section("Project · 学习项目"))
        settings.addLayout(row(self.projects, self.new_project))
        settings.addWidget(section("Source · 当前资料"))
        settings.addLayout(row(self.sources, self.new_source))
        self.suggestion = QPushButton()
        self.suggestion.hide()
        settings.addWidget(self.suggestion)
        self.connect_ai = QPushButton("重新连接")
        self.login_ai = QPushButton("登录 ChatGPT")
        self.model_choice = QComboBox()
        self.model_choice.addItem("服务默认视觉模型", "")
        settings.addWidget(section("翻译连接 · ChatGPT 订阅"))
        settings.addLayout(row(self.connect_ai, self.login_ai))
        settings.addWidget(self.model_choice)
        self.auto_notice = QLabel()
        self.auto_notice.setWordWrap(True)
        settings.addWidget(self.auto_notice)
        self.settings_panel.hide()
        self.location.toggled.connect(self.settings_panel.setVisible)
        layout.addWidget(self.settings_panel)
        self.auto_translate = QCheckBox("截图后自动翻译")
        self.connection_info = QLabel("尚未连接 · 展开上方设置可登录")
        self.connection_info.setObjectName("Meta")
        self.connection_info.setWordWrap(True)
        layout.addLayout(row(self.auto_translate, self.connection_info))

        self.thumbnail = QLabel("框选教材中需要阅读的区域\n正文、公式、电路图可以一起截")
        self.thumbnail.setObjectName("Screenshot")
        self.thumbnail.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.thumbnail.setMinimumWidth(1)
        self.thumbnail.setFixedHeight(76)
        layout.addWidget(self.thumbnail)
        self.screenshot_info = QLabel("当前没有截图")
        self.screenshot_info.setObjectName("Meta")
        layout.addWidget(self.screenshot_info)
        self.enlarge_image, self.keep_image, self.clear_image = (
            QPushButton("放大查看"), QPushButton("保留截图"), QPushButton("清除"))
        layout.addLayout(row(self.enlarge_image, self.keep_image, self.clear_image))
        for button in (self.enlarge_image, self.keep_image, self.clear_image):
            button.setEnabled(False)
        self.task_label = section("当前任务 · 翻译")
        self.task_label.hide()
        self.screenshot_translate = QPushButton("截图翻译")
        self.screenshot_explain = QPushButton("截图解释")
        layout.addLayout(row(self.screenshot_translate, self.screenshot_explain))
        self.shortcut_hint = QLabel("翻译 Alt+Q · 解释 Alt+A")
        self.shortcut_hint.setObjectName("Meta")
        self.shortcut_hint.setMaximumHeight(20)
        self.shortcut_hint.setToolTip("文字采集 Alt+Shift+Q · 更多 → 辅助文字")
        self.shortcut_hint.setWordWrap(False)
        layout.addWidget(self.shortcut_hint)
        self.result_status = section("框选教材，译文将显示在这里")
        self.result_status.setWordWrap(True)
        layout.addWidget(self.result_status)
        self.used_memory = QPushButton("尚未发送请求")
        self.used_memory.setEnabled(False)
        layout.addWidget(self.used_memory)
        self.result = ReadingResult()
        layout.addWidget(self.result, 1)
        self.translate_now = QPushButton("翻译当前内容")
        self.explain_current = QPushButton("解释这张图")
        self.copy_translation = QPushButton("复制译文")
        self.stop_translation = QPushButton("停止")
        self.retry_translation = QPushButton("重试")
        layout.addLayout(row(self.explain_current, self.copy_translation, self.stop_translation))
        layout.addWidget(self.retry_translation)
        self.followup = QuestionEdit()
        self.followup.setPlaceholderText("继续追问：为什么可以忽略 r_o？\nEnter 发送 · Shift+Enter 换行")
        self.followup.setMaxLength(1000)
        self.send_question = QPushButton("发送")
        layout.addLayout(row(self.followup, self.send_question))
        self.use_memory = QCheckBox("本次使用项目记忆")
        self.use_memory.setChecked(True)
        self.select_memory = QPushButton("指定概念／记忆")
        layout.addLayout(row(self.use_memory, self.select_memory))
        self.memory_hint = QLabel("")
        self.memory_hint.setTextFormat(Qt.TextFormat.PlainText)
        self.memory_hint.setWordWrap(True)
        self.memory_hint.hide()
        layout.addWidget(self.memory_hint)
        self.more_toggle = QPushButton("更多 · 手动转交与上下文  ▾")
        self.more_toggle.setCheckable(True)
        layout.addWidget(self.more_toggle)
        self.more_panel = QWidget()
        more = QVBoxLayout(self.more_panel)
        more.setContentsMargins(0, 0, 0, 0)
        more.addWidget(self.translate_now)
        self.more_panel.hide()
        self.more_toggle.toggled.connect(self.more_panel.setVisible)
        layout.addWidget(self.more_panel)
        self.prepare_button = QPushButton("准备给 AI")
        self.prepare_button.setObjectName("Primary")
        self.prepare_button.setEnabled(False)
        more.addWidget(self.prepare_button)
        self.handoff_panel = QWidget()
        handoff = QVBoxLayout(self.handoff_panel)
        handoff.setContentsMargins(0, 0, 0, 0)
        self.handoff_hint = QLabel()
        self.handoff_hint.setWordWrap(True)
        handoff.addWidget(self.handoff_hint)
        self.copy_image_button = QPushButton("重新复制截图")
        self.copy_button = QPushButton("复制说明")
        self.copy_button.setEnabled(False)
        handoff.addLayout(row(self.copy_image_button, self.copy_button))
        self.ai_target = QComboBox()
        self.ai_target.addItems(["ChatGPT", "Claude"])
        self.open_ai = QPushButton("打开所选 AI")
        handoff.addLayout(row(self.ai_target, self.open_ai))
        self.handoff_panel.hide()
        more.addWidget(self.handoff_panel)

        self.text_toggle = QPushButton("辅助文字  ▾")
        self.text_toggle.setCheckable(True)
        more.addWidget(self.text_toggle)
        self.text_panel = QWidget()
        text_layout = QVBoxLayout(self.text_panel)
        text_layout.setContentsMargins(0, 0, 0, 0)
        self.selection_label = section("辅助文字 · Alt+Shift+Q")
        self.selection = QPlainTextEdit()
        self.selection.setObjectName("selection")
        self.selection.setPlaceholderText("有文字层时可采集或粘贴；截图翻译无需先提取文字。")
        self.selection.setFixedHeight(110)
        self.text_capture = QPushButton("3 秒后采集选文")
        text_layout.addWidget(self.selection_label)
        text_layout.addWidget(self.selection)
        text_layout.addWidget(self.text_capture)
        self.text_panel.hide()
        self.text_toggle.toggled.connect(self.text_panel.setVisible)
        more.addWidget(self.text_panel)

        self.details_toggle = QPushButton("详情与上下文  ▾")
        self.details_toggle.setCheckable(True)
        more.addWidget(self.details_toggle)
        self.details_panel = QWidget()
        details = QVBoxLayout(self.details_panel)
        details.setContentsMargins(0, 0, 0, 0)
        self.topic = QLineEdit()
        self.topic.setMaxLength(200)
        self.topic.setPlaceholderText("Topic（可选，帮助检索相关知识）")
        details.addWidget(self.topic)
        self.session = QLabel("Session · 尚未开始")
        self.window_info = QLabel("当前应用：待采集")
        self.window_info.setTextFormat(Qt.TextFormat.PlainText)
        self.window_info.setWordWrap(True)
        details.addWidget(self.session)
        details.addWidget(self.window_info)
        self.recent_images = QComboBox()
        self.recent_images.addItem("本次学习的最近截图", None)
        details.addWidget(self.recent_images)
        self.tabs = QTabWidget()
        self.knowledge, self.memories, self.preview = QPlainTextEdit(), QPlainTextEdit(), QPlainTextEdit()
        for widget, name in ((self.knowledge, "相关知识"), (self.memories, "学习记忆"), (self.preview, "完整说明")):
            widget.setReadOnly(True)
            self.tabs.addTab(widget, name)
        self.tabs.setMinimumHeight(190)
        self.preview.setObjectName("preview")
        details.addWidget(self.tabs)
        self.package_info = QLabel("仅携带必要上下文")
        self.package_info.setWordWrap(True)
        details.addWidget(self.package_info)
        self.details_panel.hide()
        self.details_toggle.toggled.connect(self.details_panel.setVisible)
        more.addWidget(self.details_panel)
        layout.addStretch()

        self.status = QLabel("点击截图翻译，框选后在这里阅读。")
        self.status.setTextFormat(Qt.TextFormat.PlainText)
        self.status.setObjectName("Status")
        self.status.setWordWrap(True)
        outer.addWidget(self.status)
        self.save_memory, self.close_button = QPushButton("记住这个疑问"), QPushButton("关闭")
        self.manage_memory = QPushButton("项目记忆")
        self.close_button.clicked.connect(self.close)
        outer.addLayout(row(self.save_memory, self.manage_memory, self.close_button))
        self.privacy = privacy = QLabel("仅主动截图 · 自动发送已关闭")
        privacy.setObjectName("Meta")
        privacy.setAlignment(Qt.AlignmentFlag.AlignCenter)
        outer.addWidget(privacy)

    def set_capture_shortcut(self, shortcut: str | None):
        self.selection_label.setText("辅助文字 · " + (shortcut or "手动粘贴"))

    def set_image(self, image: QPixmap | None):
        self.image = image or QPixmap()
        self.update_thumbnail()

    def update_thumbnail(self):
        if self.image.isNull():
            self.thumbnail.setPixmap(QPixmap())
            self.thumbnail.setText("框选教材中需要阅读的区域\n正文、公式、电路图可以一起截")
        else:
            self.thumbnail.setPixmap(self.image.scaled(
                self.thumbnail.size() - QSize(18, 18), Qt.AspectRatioMode.KeepAspectRatio,
                Qt.TransformationMode.SmoothTransformation))

    def resizeEvent(self, event):
        super().resizeEvent(event)
        self.update_thumbnail()

    def place_right(self):
        screen = QApplication.primaryScreen()
        if screen:
            rect = screen.availableGeometry()
            self.resize(430, min(820, rect.height() - 40))
            self.move(rect.right() - self.width() - 15, rect.top() + 20)

    def closeEvent(self, event):
        self.closing.emit()
        event.accept()
